### ISSUE TITLE
PSGIで動作するMovableTypeでアクセスカウントができない

### ISSUE THREAD

**Issue by harakachi** [morimasato/mt-plugin-accesscounter#1]
初めまして。
AWS + MT6 の環境でこちらのアクセスカウンターを利用しようとしたところ
HTMLに埋め込まれる AccessCounter.cgi が NotFound となってしまう事象が発生していました。
おそらくPSGIで動くMovableTypeの場合、applicationsにcgiを明示的に追加しないといけないようです。
こちらでは下記のような差分を追記することで動くことを確認いたしました。

AccessCounter.pl

```
registry => {
            applications      => {
                'AccessCounter' => {
                    handler  => 'AccessCounter',
                    script   => sub { default => 'AccessCounter.cgi' },
                    cgi_path => sub { default => '/mt/plugins/AccessCounter' },
                },
            },
```

以上、ご報告でした。
宜しくお願いいたします。

**Comment by morimasato** [comment]
harakachiさま
ご連絡ありがとうございました。
とても有益な情報をありがとうございました。
なるべく早めに対応いたします。

**Comment by morimasato** [comment]
fixed PSGI
