### ISSUE TITLE
JSを読み込ませないオプション

### ISSUE THREAD

**Issue by sueharaluke** [morimasato/mt-plugin-accesscounter#3]
お世話になっております。

プラグインの開発、ありがとうございました。非常に助かっています。

1点だけ、教えて頂ければと思います。
AMPページを作成しておりまして、JSを使っていはいけないです。そのため、AMPページについては、ランキンングを表示し、JSを入れないという方法はありますでしょうか？
(AMPページのアクセス数は取得しなくてもよいです)

よろしくお願い致します。

**Comment by morimasato** [comment]
お問い合わせありがとうございます。
当該ページはjsタグを追加しない条件分岐で対応できそうですね。
プラグインのカスタマイズが必要です。
頑張ってください。

2017年11月9日(木) 15:55 Lucas Suehara <notifications@github.com>:

**Comment by sueharaluke** [comment]
@morimasato 

早速、お返事ありがとうございました！

Perlと戦いながら、やってみます。:sweat_smile:

**Comment by sueharaluke** [comment]
しばらく経ちましたが、解決できましたので、よかったら Pull request をご承認・編集頂けたらと思います。
https://github.com/morimasato/mt-plugin-accesscounter/pull/4

よろしくお願い致します。
